/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.jcc.xtext.simpleAgent;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Behavior</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.Behavior#getPlanner <em>Planner</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.Behavior#getStart <em>Start</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.Behavior#getInit <em>Init</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.Behavior#getActions <em>Actions</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.Behavior#getOnGoalReached <em>On Goal Reached</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.Behavior#getOnSuspended <em>On Suspended</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.Behavior#getOnResumed <em>On Resumed</em>}</li>
 * </ul>
 *
 * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getBehavior()
 * @model
 * @generated
 */
public interface Behavior extends BehaviorDeclaration
{
  /**
   * Returns the value of the '<em><b>Planner</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Planner</em>' attribute.
   * @see #setPlanner(String)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getBehavior_Planner()
   * @model
   * @generated
   */
  String getPlanner();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.Behavior#getPlanner <em>Planner</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Planner</em>' attribute.
   * @see #getPlanner()
   * @generated
   */
  void setPlanner(String value);

  /**
   * Returns the value of the '<em><b>Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' containment reference.
   * @see #setStart(AnyAction)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getBehavior_Start()
   * @model containment="true"
   * @generated
   */
  AnyAction getStart();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.Behavior#getStart <em>Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' containment reference.
   * @see #getStart()
   * @generated
   */
  void setStart(AnyAction value);

  /**
   * Returns the value of the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init</em>' containment reference.
   * @see #setInit(ActionBody)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getBehavior_Init()
   * @model containment="true"
   * @generated
   */
  ActionBody getInit();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.Behavior#getInit <em>Init</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init</em>' containment reference.
   * @see #getInit()
   * @generated
   */
  void setInit(ActionBody value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link it.unibo.jcc.xtext.simpleAgent.Action}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getBehavior_Actions()
   * @model containment="true"
   * @generated
   */
  EList<Action> getActions();

  /**
   * Returns the value of the '<em><b>On Goal Reached</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>On Goal Reached</em>' containment reference.
   * @see #setOnGoalReached(ActionBody)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getBehavior_OnGoalReached()
   * @model containment="true"
   * @generated
   */
  ActionBody getOnGoalReached();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.Behavior#getOnGoalReached <em>On Goal Reached</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>On Goal Reached</em>' containment reference.
   * @see #getOnGoalReached()
   * @generated
   */
  void setOnGoalReached(ActionBody value);

  /**
   * Returns the value of the '<em><b>On Suspended</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>On Suspended</em>' containment reference.
   * @see #setOnSuspended(ActionBody)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getBehavior_OnSuspended()
   * @model containment="true"
   * @generated
   */
  ActionBody getOnSuspended();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.Behavior#getOnSuspended <em>On Suspended</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>On Suspended</em>' containment reference.
   * @see #getOnSuspended()
   * @generated
   */
  void setOnSuspended(ActionBody value);

  /**
   * Returns the value of the '<em><b>On Resumed</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>On Resumed</em>' containment reference.
   * @see #setOnResumed(ActionBody)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getBehavior_OnResumed()
   * @model containment="true"
   * @generated
   */
  ActionBody getOnResumed();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.Behavior#getOnResumed <em>On Resumed</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>On Resumed</em>' containment reference.
   * @see #getOnResumed()
   * @generated
   */
  void setOnResumed(ActionBody value);

} // Behavior
