/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.jcc.xtext.simpleAgent;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Behavior External</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.BehaviorExternal#getContext <em>Context</em>}</li>
 * </ul>
 *
 * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getBehaviorExternal()
 * @model
 * @generated
 */
public interface BehaviorExternal extends BehaviorDeclaration
{
  /**
   * Returns the value of the '<em><b>Context</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context</em>' reference.
   * @see #setContext(Context)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getBehaviorExternal_Context()
   * @model
   * @generated
   */
  Context getContext();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.BehaviorExternal#getContext <em>Context</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context</em>' reference.
   * @see #getContext()
   * @generated
   */
  void setContext(Context value);

} // BehaviorExternal
