/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.jcc.xtext.simpleAgent;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Broker Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.BrokerSpec#getBrokerHost <em>Broker Host</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.BrokerSpec#getBrokerPort <em>Broker Port</em>}</li>
 * </ul>
 *
 * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getBrokerSpec()
 * @model
 * @generated
 */
public interface BrokerSpec extends EObject
{
  /**
   * Returns the value of the '<em><b>Broker Host</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Broker Host</em>' attribute.
   * @see #setBrokerHost(String)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getBrokerSpec_BrokerHost()
   * @model
   * @generated
   */
  String getBrokerHost();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.BrokerSpec#getBrokerHost <em>Broker Host</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Broker Host</em>' attribute.
   * @see #getBrokerHost()
   * @generated
   */
  void setBrokerHost(String value);

  /**
   * Returns the value of the '<em><b>Broker Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Broker Port</em>' attribute.
   * @see #setBrokerPort(int)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getBrokerSpec_BrokerPort()
   * @model
   * @generated
   */
  int getBrokerPort();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.BrokerSpec#getBrokerPort <em>Broker Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Broker Port</em>' attribute.
   * @see #getBrokerPort()
   * @generated
   */
  void setBrokerPort(int value);

} // BrokerSpec
