/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.jcc.xtext.simpleAgent;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Code Run Simple</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getCodeRunSimple()
 * @model
 * @generated
 */
public interface CodeRunSimple extends CodeRun
{
} // CodeRunSimple
