/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.jcc.xtext.simpleAgent;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.Context#getName <em>Name</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.Context#getIp <em>Ip</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.Context#isMqtt <em>Mqtt</em>}</li>
 * </ul>
 *
 * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getContext()
 * @model
 * @generated
 */
public interface Context extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getContext_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.Context#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ip</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ip</em>' containment reference.
   * @see #setIp(ComponentIP)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getContext_Ip()
   * @model containment="true"
   * @generated
   */
  ComponentIP getIp();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.Context#getIp <em>Ip</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ip</em>' containment reference.
   * @see #getIp()
   * @generated
   */
  void setIp(ComponentIP value);

  /**
   * Returns the value of the '<em><b>Mqtt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mqtt</em>' attribute.
   * @see #setMqtt(boolean)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getContext_Mqtt()
   * @model
   * @generated
   */
  boolean isMqtt();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.Context#isMqtt <em>Mqtt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mqtt</em>' attribute.
   * @see #isMqtt()
   * @generated
   */
  void setMqtt(boolean value);

} // Context
