/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.jcc.xtext.simpleAgent;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Forward</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.Forward#getDest <em>Dest</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.Forward#getMsgref <em>Msgref</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.Forward#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getForward()
 * @model
 * @generated
 */
public interface Forward extends StateAction
{
  /**
   * Returns the value of the '<em><b>Dest</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dest</em>' reference.
   * @see #setDest(BehaviorDeclaration)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getForward_Dest()
   * @model
   * @generated
   */
  BehaviorDeclaration getDest();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.Forward#getDest <em>Dest</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dest</em>' reference.
   * @see #getDest()
   * @generated
   */
  void setDest(BehaviorDeclaration value);

  /**
   * Returns the value of the '<em><b>Msgref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Msgref</em>' reference.
   * @see #setMsgref(Message)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getForward_Msgref()
   * @model
   * @generated
   */
  Message getMsgref();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.Forward#getMsgref <em>Msgref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Msgref</em>' reference.
   * @see #getMsgref()
   * @generated
   */
  void setMsgref(Message value);

  /**
   * Returns the value of the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' containment reference.
   * @see #setVal(PHead)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getForward_Val()
   * @model containment="true"
   * @generated
   */
  PHead getVal();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.Forward#getVal <em>Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' containment reference.
   * @see #getVal()
   * @generated
   */
  void setVal(PHead value);

} // Forward
