/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.jcc.xtext.simpleAgent;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Msg Cond</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.MsgCond#getMessage <em>Message</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.MsgCond#getMsg <em>Msg</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.MsgCond#getActions <em>Actions</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.MsgCond#getIfnot <em>Ifnot</em>}</li>
 * </ul>
 *
 * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getMsgCond()
 * @model
 * @generated
 */
public interface MsgCond extends StateAction
{
  /**
   * Returns the value of the '<em><b>Message</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' reference.
   * @see #setMessage(Message)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getMsgCond_Message()
   * @model
   * @generated
   */
  Message getMessage();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.MsgCond#getMessage <em>Message</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' reference.
   * @see #getMessage()
   * @generated
   */
  void setMessage(Message value);

  /**
   * Returns the value of the '<em><b>Msg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Msg</em>' containment reference.
   * @see #setMsg(PHead)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getMsgCond_Msg()
   * @model containment="true"
   * @generated
   */
  PHead getMsg();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.MsgCond#getMsg <em>Msg</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Msg</em>' containment reference.
   * @see #getMsg()
   * @generated
   */
  void setMsg(PHead value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link it.unibo.jcc.xtext.simpleAgent.GuardedStateAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getMsgCond_Actions()
   * @model containment="true"
   * @generated
   */
  EList<GuardedStateAction> getActions();

  /**
   * Returns the value of the '<em><b>Ifnot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ifnot</em>' containment reference.
   * @see #setIfnot(NoMsgCond)
   * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getMsgCond_Ifnot()
   * @model containment="true"
   * @generated
   */
  NoMsgCond getIfnot();

  /**
   * Sets the value of the '{@link it.unibo.jcc.xtext.simpleAgent.MsgCond#getIfnot <em>Ifnot</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ifnot</em>' containment reference.
   * @see #getIfnot()
   * @generated
   */
  void setIfnot(NoMsgCond value);

} // MsgCond
