/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.jcc.xtext.simpleAgent;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PAtom</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage#getPAtom()
 * @model
 * @generated
 */
public interface PAtom extends PHead
{
} // PAtom
