/*
 * generated by Xtext 2.17.0
 */
package it.unibo.jcc.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SimpleAgentStandaloneSetup extends SimpleAgentStandaloneSetupGenerated {

	def static void doSetup() {
		new SimpleAgentStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
