/**
 * generated by Xtext 2.17.0
 */
package it.unibo.jcc.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.unibo.jcc.xtext.SimpleAgentRuntimeModule;
import it.unibo.jcc.xtext.SimpleAgentStandaloneSetup;
import it.unibo.jcc.xtext.ide.SimpleAgentIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SimpleAgentIdeSetup extends SimpleAgentStandaloneSetup {
  @Override
  public Injector createInjector() {
    SimpleAgentRuntimeModule _simpleAgentRuntimeModule = new SimpleAgentRuntimeModule();
    SimpleAgentIdeModule _simpleAgentIdeModule = new SimpleAgentIdeModule();
    return Guice.createInjector(Modules2.mixin(_simpleAgentRuntimeModule, _simpleAgentIdeModule));
  }
}
