/*
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.jcc.xtext.ui.tests;

import com.google.inject.Injector;
import it.unibo.jcc.xtext.simpleagent.ui.internal.SimpleagentActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SimpleAgentUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SimpleagentActivator.getInstance().getInjector("it.unibo.jcc.xtext.SimpleAgent");
	}

}
