/*
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.jcc.xtext.parser.antlr;

import com.google.inject.Inject;
import it.unibo.jcc.xtext.parser.antlr.internal.InternalSimpleAgentParser;
import it.unibo.jcc.xtext.services.SimpleAgentGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SimpleAgentParser extends AbstractAntlrParser {

	@Inject
	private SimpleAgentGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSimpleAgentParser createParser(XtextTokenStream stream) {
		return new InternalSimpleAgentParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SimpleAgent";
	}

	public SimpleAgentGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimpleAgentGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
