/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.jcc.xtext.simpleAgent.impl;

import it.unibo.jcc.xtext.simpleAgent.BehaviorDeclaration;
import it.unibo.jcc.xtext.simpleAgent.ComponentIP;
import it.unibo.jcc.xtext.simpleAgent.QActorSystemSpec;
import it.unibo.jcc.xtext.simpleAgent.SimpleAgent;
import it.unibo.jcc.xtext.simpleAgent.SimpleAgentPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Agent</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.impl.SimpleAgentImpl#getName <em>Name</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.impl.SimpleAgentImpl#getIp <em>Ip</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.impl.SimpleAgentImpl#getMqtt <em>Mqtt</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.impl.SimpleAgentImpl#getSystem <em>System</em>}</li>
 *   <li>{@link it.unibo.jcc.xtext.simpleAgent.impl.SimpleAgentImpl#getBehaviors <em>Behaviors</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SimpleAgentImpl extends MinimalEObjectImpl.Container implements SimpleAgent
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getIp() <em>Ip</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIp()
   * @generated
   * @ordered
   */
  protected ComponentIP ip;

  /**
   * The default value of the '{@link #getMqtt() <em>Mqtt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMqtt()
   * @generated
   * @ordered
   */
  protected static final String MQTT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMqtt() <em>Mqtt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMqtt()
   * @generated
   * @ordered
   */
  protected String mqtt = MQTT_EDEFAULT;

  /**
   * The cached value of the '{@link #getSystem() <em>System</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSystem()
   * @generated
   * @ordered
   */
  protected QActorSystemSpec system;

  /**
   * The cached value of the '{@link #getBehaviors() <em>Behaviors</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBehaviors()
   * @generated
   * @ordered
   */
  protected EList<BehaviorDeclaration> behaviors;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleAgentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SimpleAgentPackage.Literals.SIMPLE_AGENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimpleAgentPackage.SIMPLE_AGENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComponentIP getIp()
  {
    return ip;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIp(ComponentIP newIp, NotificationChain msgs)
  {
    ComponentIP oldIp = ip;
    ip = newIp;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SimpleAgentPackage.SIMPLE_AGENT__IP, oldIp, newIp);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIp(ComponentIP newIp)
  {
    if (newIp != ip)
    {
      NotificationChain msgs = null;
      if (ip != null)
        msgs = ((InternalEObject)ip).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SimpleAgentPackage.SIMPLE_AGENT__IP, null, msgs);
      if (newIp != null)
        msgs = ((InternalEObject)newIp).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SimpleAgentPackage.SIMPLE_AGENT__IP, null, msgs);
      msgs = basicSetIp(newIp, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimpleAgentPackage.SIMPLE_AGENT__IP, newIp, newIp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMqtt()
  {
    return mqtt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMqtt(String newMqtt)
  {
    String oldMqtt = mqtt;
    mqtt = newMqtt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimpleAgentPackage.SIMPLE_AGENT__MQTT, oldMqtt, mqtt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QActorSystemSpec getSystem()
  {
    return system;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSystem(QActorSystemSpec newSystem, NotificationChain msgs)
  {
    QActorSystemSpec oldSystem = system;
    system = newSystem;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SimpleAgentPackage.SIMPLE_AGENT__SYSTEM, oldSystem, newSystem);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSystem(QActorSystemSpec newSystem)
  {
    if (newSystem != system)
    {
      NotificationChain msgs = null;
      if (system != null)
        msgs = ((InternalEObject)system).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SimpleAgentPackage.SIMPLE_AGENT__SYSTEM, null, msgs);
      if (newSystem != null)
        msgs = ((InternalEObject)newSystem).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SimpleAgentPackage.SIMPLE_AGENT__SYSTEM, null, msgs);
      msgs = basicSetSystem(newSystem, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimpleAgentPackage.SIMPLE_AGENT__SYSTEM, newSystem, newSystem));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BehaviorDeclaration> getBehaviors()
  {
    if (behaviors == null)
    {
      behaviors = new EObjectContainmentEList<BehaviorDeclaration>(BehaviorDeclaration.class, this, SimpleAgentPackage.SIMPLE_AGENT__BEHAVIORS);
    }
    return behaviors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SimpleAgentPackage.SIMPLE_AGENT__IP:
        return basicSetIp(null, msgs);
      case SimpleAgentPackage.SIMPLE_AGENT__SYSTEM:
        return basicSetSystem(null, msgs);
      case SimpleAgentPackage.SIMPLE_AGENT__BEHAVIORS:
        return ((InternalEList<?>)getBehaviors()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SimpleAgentPackage.SIMPLE_AGENT__NAME:
        return getName();
      case SimpleAgentPackage.SIMPLE_AGENT__IP:
        return getIp();
      case SimpleAgentPackage.SIMPLE_AGENT__MQTT:
        return getMqtt();
      case SimpleAgentPackage.SIMPLE_AGENT__SYSTEM:
        return getSystem();
      case SimpleAgentPackage.SIMPLE_AGENT__BEHAVIORS:
        return getBehaviors();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SimpleAgentPackage.SIMPLE_AGENT__NAME:
        setName((String)newValue);
        return;
      case SimpleAgentPackage.SIMPLE_AGENT__IP:
        setIp((ComponentIP)newValue);
        return;
      case SimpleAgentPackage.SIMPLE_AGENT__MQTT:
        setMqtt((String)newValue);
        return;
      case SimpleAgentPackage.SIMPLE_AGENT__SYSTEM:
        setSystem((QActorSystemSpec)newValue);
        return;
      case SimpleAgentPackage.SIMPLE_AGENT__BEHAVIORS:
        getBehaviors().clear();
        getBehaviors().addAll((Collection<? extends BehaviorDeclaration>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SimpleAgentPackage.SIMPLE_AGENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case SimpleAgentPackage.SIMPLE_AGENT__IP:
        setIp((ComponentIP)null);
        return;
      case SimpleAgentPackage.SIMPLE_AGENT__MQTT:
        setMqtt(MQTT_EDEFAULT);
        return;
      case SimpleAgentPackage.SIMPLE_AGENT__SYSTEM:
        setSystem((QActorSystemSpec)null);
        return;
      case SimpleAgentPackage.SIMPLE_AGENT__BEHAVIORS:
        getBehaviors().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SimpleAgentPackage.SIMPLE_AGENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case SimpleAgentPackage.SIMPLE_AGENT__IP:
        return ip != null;
      case SimpleAgentPackage.SIMPLE_AGENT__MQTT:
        return MQTT_EDEFAULT == null ? mqtt != null : !MQTT_EDEFAULT.equals(mqtt);
      case SimpleAgentPackage.SIMPLE_AGENT__SYSTEM:
        return system != null;
      case SimpleAgentPackage.SIMPLE_AGENT__BEHAVIORS:
        return behaviors != null && !behaviors.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", mqtt: ");
    result.append(mqtt);
    result.append(')');
    return result.toString();
  }

} //SimpleAgentImpl
