/**
 * generated by Xtext 2.17.0
 */
package it.unibo.jcc.xtext;

import it.unibo.jcc.xtext.SimpleAgentStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SimpleAgentStandaloneSetup extends SimpleAgentStandaloneSetupGenerated {
  public static void doSetup() {
    new SimpleAgentStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
