/**
 * generated by Xtext 2.17.0
 */
package it.unibo.jcc.xtext.ui;

import it.unibo.jcc.xtext.ui.AbstractSimpleAgentUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SimpleAgentUiModule extends AbstractSimpleAgentUiModule {
  public SimpleAgentUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
