/*
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.jcc.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import it.unibo.jcc.xtext.ide.contentassist.antlr.internal.InternalSimpleAgentParser;
import it.unibo.jcc.xtext.services.SimpleAgentGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class SimpleAgentParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SimpleAgentGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SimpleAgentGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getBehaviorDeclarationAccess().getAlternatives(), "rule__BehaviorDeclaration__Alternatives");
			builder.put(grammarAccess.getCompensationAccess().getAlternatives(), "rule__Compensation__Alternatives");
			builder.put(grammarAccess.getCodeRunArgAccess().getAlternatives(), "rule__CodeRunArg__Alternatives");
			builder.put(grammarAccess.getBuiltinVarAccess().getAlternatives(), "rule__BuiltinVar__Alternatives");
			builder.put(grammarAccess.getMessageAccess().getAlternatives(), "rule__Message__Alternatives");
			builder.put(grammarAccess.getOutOnlyMessageAccess().getAlternatives(), "rule__OutOnlyMessage__Alternatives");
			builder.put(grammarAccess.getOutInMessageAccess().getAlternatives(), "rule__OutInMessage__Alternatives");
			builder.put(grammarAccess.getGuardedStateActionAccess().getAlternatives_0(), "rule__GuardedStateAction__Alternatives_0");
			builder.put(grammarAccess.getStateActionAccess().getAlternatives(), "rule__StateAction__Alternatives");
			builder.put(grammarAccess.getDelayAccess().getAlternatives(), "rule__Delay__Alternatives");
			builder.put(grammarAccess.getCodeRunAccess().getAlternatives(), "rule__CodeRun__Alternatives");
			builder.put(grammarAccess.getPHeadAccess().getAlternatives(), "rule__PHead__Alternatives");
			builder.put(grammarAccess.getPAtomAccess().getAlternatives(), "rule__PAtom__Alternatives");
			builder.put(grammarAccess.getSimpleAgentAccess().getGroup(), "rule__SimpleAgent__Group__0");
			builder.put(grammarAccess.getQActorSystemSpecAccess().getGroup(), "rule__QActorSystemSpec__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getBehaviorAccess().getGroup(), "rule__Behavior__Group__0");
			builder.put(grammarAccess.getBehaviorAccess().getGroup_6(), "rule__Behavior__Group_6__0");
			builder.put(grammarAccess.getBehaviorAccess().getGroup_8(), "rule__Behavior__Group_8__0");
			builder.put(grammarAccess.getBehaviorAccess().getGroup_9(), "rule__Behavior__Group_9__0");
			builder.put(grammarAccess.getBehaviorAccess().getGroup_10(), "rule__Behavior__Group_10__0");
			builder.put(grammarAccess.getBehaviorExternalAccess().getGroup(), "rule__BehaviorExternal__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup_2(), "rule__Action__Group_2__0");
			builder.put(grammarAccess.getOnEffectAccess().getGroup(), "rule__OnEffect__Group__0");
			builder.put(grammarAccess.getCompensationAccess().getGroup_0(), "rule__Compensation__Group_0__0");
			builder.put(grammarAccess.getCompensationAccess().getGroup_0_3(), "rule__Compensation__Group_0_3__0");
			builder.put(grammarAccess.getCompensationAccess().getGroup_1(), "rule__Compensation__Group_1__0");
			builder.put(grammarAccess.getCompensationAccess().getGroup_1_3(), "rule__Compensation__Group_1_3__0");
			builder.put(grammarAccess.getCompensationAccess().getGroup_2(), "rule__Compensation__Group_2__0");
			builder.put(grammarAccess.getCompensationAccess().getGroup_2_4(), "rule__Compensation__Group_2_4__0");
			builder.put(grammarAccess.getActionBodyAccess().getGroup(), "rule__ActionBody__Group__0");
			builder.put(grammarAccess.getCodeRunArgAccess().getGroup_1(), "rule__CodeRunArg__Group_1__0");
			builder.put(grammarAccess.getBrokerSpecAccess().getGroup(), "rule__BrokerSpec__Group__0");
			builder.put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
			builder.put(grammarAccess.getSignalAccess().getGroup(), "rule__Signal__Group__0");
			builder.put(grammarAccess.getTokenAccess().getGroup(), "rule__Token__Group__0");
			builder.put(grammarAccess.getDispatchAccess().getGroup(), "rule__Dispatch__Group__0");
			builder.put(grammarAccess.getRequestAccess().getGroup(), "rule__Request__Group__0");
			builder.put(grammarAccess.getInvitationAccess().getGroup(), "rule__Invitation__Group__0");
			builder.put(grammarAccess.getContextAccess().getGroup(), "rule__Context__Group__0");
			builder.put(grammarAccess.getComponentIPAccess().getGroup(), "rule__ComponentIP__Group__0");
			builder.put(grammarAccess.getGuardedStateActionAccess().getGroup(), "rule__GuardedStateAction__Group__0");
			builder.put(grammarAccess.getGuardedStateActionAccess().getGroup_0_0(), "rule__GuardedStateAction__Group_0_0__0");
			builder.put(grammarAccess.getGuardedStateActionAccess().getGroup_2(), "rule__GuardedStateAction__Group_2__0");
			builder.put(grammarAccess.getPrintCurMsgAccess().getGroup(), "rule__PrintCurMsg__Group__0");
			builder.put(grammarAccess.getPrintAccess().getGroup(), "rule__Print__Group__0");
			builder.put(grammarAccess.getSolveGoalAccess().getGroup(), "rule__SolveGoal__Group__0");
			builder.put(grammarAccess.getSolveGoalAccess().getGroup_4(), "rule__SolveGoal__Group_4__0");
			builder.put(grammarAccess.getForwardAccess().getGroup(), "rule__Forward__Group__0");
			builder.put(grammarAccess.getEmitAccess().getGroup(), "rule__Emit__Group__0");
			builder.put(grammarAccess.getDelayIntAccess().getGroup(), "rule__DelayInt__Group__0");
			builder.put(grammarAccess.getDelayVarAccess().getGroup(), "rule__DelayVar__Group__0");
			builder.put(grammarAccess.getDelayVrefAccess().getGroup(), "rule__DelayVref__Group__0");
			builder.put(grammarAccess.getDelaySolAccess().getGroup(), "rule__DelaySol__Group__0");
			builder.put(grammarAccess.getMsgCondAccess().getGroup(), "rule__MsgCond__Group__0");
			builder.put(grammarAccess.getMsgCondAccess().getGroup_9(), "rule__MsgCond__Group_9__0");
			builder.put(grammarAccess.getNoMsgCondAccess().getGroup(), "rule__NoMsgCond__Group__0");
			builder.put(grammarAccess.getAnyActionAccess().getGroup(), "rule__AnyAction__Group__0");
			builder.put(grammarAccess.getCodeRunActorAccess().getGroup(), "rule__CodeRunActor__Group__0");
			builder.put(grammarAccess.getCodeRunActorAccess().getGroup_4(), "rule__CodeRunActor__Group_4__0");
			builder.put(grammarAccess.getCodeRunActorAccess().getGroup_4_2(), "rule__CodeRunActor__Group_4_2__0");
			builder.put(grammarAccess.getCodeRunSimpleAccess().getGroup(), "rule__CodeRunSimple__Group__0");
			builder.put(grammarAccess.getCodeRunSimpleAccess().getGroup_3(), "rule__CodeRunSimple__Group_3__0");
			builder.put(grammarAccess.getCodeRunSimpleAccess().getGroup_3_1(), "rule__CodeRunSimple__Group_3_1__0");
			builder.put(grammarAccess.getExecAccess().getGroup(), "rule__Exec__Group__0");
			builder.put(grammarAccess.getPStructRefAccess().getGroup(), "rule__PStructRef__Group__0");
			builder.put(grammarAccess.getPStructAccess().getGroup(), "rule__PStruct__Group__0");
			builder.put(grammarAccess.getPStructAccess().getGroup_3(), "rule__PStruct__Group_3__0");
			builder.put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
			builder.put(grammarAccess.getVarRefAccess().getGroup(), "rule__VarRef__Group__0");
			builder.put(grammarAccess.getVarRefInStrAccess().getGroup(), "rule__VarRefInStr__Group__0");
			builder.put(grammarAccess.getVarSolRefAccess().getGroup(), "rule__VarSolRef__Group__0");
			builder.put(grammarAccess.getSimpleAgentAccess().getNameAssignment_1(), "rule__SimpleAgent__NameAssignment_1");
			builder.put(grammarAccess.getSimpleAgentAccess().getIpAssignment_3(), "rule__SimpleAgent__IpAssignment_3");
			builder.put(grammarAccess.getSimpleAgentAccess().getMqttAssignment_4(), "rule__SimpleAgent__MqttAssignment_4");
			builder.put(grammarAccess.getSimpleAgentAccess().getSystemAssignment_7(), "rule__SimpleAgent__SystemAssignment_7");
			builder.put(grammarAccess.getSimpleAgentAccess().getBehaviorsAssignment_9(), "rule__SimpleAgent__BehaviorsAssignment_9");
			builder.put(grammarAccess.getQActorSystemSpecAccess().getMqttBrokerAssignment_1(), "rule__QActorSystemSpec__MqttBrokerAssignment_1");
			builder.put(grammarAccess.getQActorSystemSpecAccess().getMessageAssignment_2(), "rule__QActorSystemSpec__MessageAssignment_2");
			builder.put(grammarAccess.getQActorSystemSpecAccess().getContextAssignment_3(), "rule__QActorSystemSpec__ContextAssignment_3");
			builder.put(grammarAccess.getBehaviorAccess().getNameAssignment_1(), "rule__Behavior__NameAssignment_1");
			builder.put(grammarAccess.getBehaviorAccess().getPlannerAssignment_3(), "rule__Behavior__PlannerAssignment_3");
			builder.put(grammarAccess.getBehaviorAccess().getStartAssignment_5(), "rule__Behavior__StartAssignment_5");
			builder.put(grammarAccess.getBehaviorAccess().getInitAssignment_6_2(), "rule__Behavior__InitAssignment_6_2");
			builder.put(grammarAccess.getBehaviorAccess().getActionsAssignment_7(), "rule__Behavior__ActionsAssignment_7");
			builder.put(grammarAccess.getBehaviorAccess().getOnGoalReachedAssignment_8_2(), "rule__Behavior__OnGoalReachedAssignment_8_2");
			builder.put(grammarAccess.getBehaviorAccess().getOnSuspendedAssignment_9_2(), "rule__Behavior__OnSuspendedAssignment_9_2");
			builder.put(grammarAccess.getBehaviorAccess().getOnResumedAssignment_10_2(), "rule__Behavior__OnResumedAssignment_10_2");
			builder.put(grammarAccess.getBehaviorExternalAccess().getNameAssignment_1(), "rule__BehaviorExternal__NameAssignment_1");
			builder.put(grammarAccess.getBehaviorExternalAccess().getContextAssignment_3(), "rule__BehaviorExternal__ContextAssignment_3");
			builder.put(grammarAccess.getActionAccess().getActionsAssignment_1(), "rule__Action__ActionsAssignment_1");
			builder.put(grammarAccess.getActionAccess().getActionsAssignment_2_1(), "rule__Action__ActionsAssignment_2_1");
			builder.put(grammarAccess.getActionAccess().getBodyAssignment_4(), "rule__Action__BodyAssignment_4");
			builder.put(grammarAccess.getActionAccess().getOnAssignment_6(), "rule__Action__OnAssignment_6");
			builder.put(grammarAccess.getOnEffectAccess().getEffectAssignment_2(), "rule__OnEffect__EffectAssignment_2");
			builder.put(grammarAccess.getOnEffectAccess().getBodyAssignment_5(), "rule__OnEffect__BodyAssignment_5");
			builder.put(grammarAccess.getOnEffectAccess().getCompensationsAssignment_7(), "rule__OnEffect__CompensationsAssignment_7");
			builder.put(grammarAccess.getCompensationAccess().getTypeAssignment_0_0(), "rule__Compensation__TypeAssignment_0_0");
			builder.put(grammarAccess.getCompensationAccess().getConditionAssignment_0_2(), "rule__Compensation__ConditionAssignment_0_2");
			builder.put(grammarAccess.getCompensationAccess().getBodyAssignment_0_3_1(), "rule__Compensation__BodyAssignment_0_3_1");
			builder.put(grammarAccess.getCompensationAccess().getTypeAssignment_1_0(), "rule__Compensation__TypeAssignment_1_0");
			builder.put(grammarAccess.getCompensationAccess().getConditionAssignment_1_2(), "rule__Compensation__ConditionAssignment_1_2");
			builder.put(grammarAccess.getCompensationAccess().getBodyAssignment_1_3_1(), "rule__Compensation__BodyAssignment_1_3_1");
			builder.put(grammarAccess.getCompensationAccess().getTypeAssignment_2_0(), "rule__Compensation__TypeAssignment_2_0");
			builder.put(grammarAccess.getCompensationAccess().getGoalAssignment_2_1(), "rule__Compensation__GoalAssignment_2_1");
			builder.put(grammarAccess.getCompensationAccess().getConditionAssignment_2_3(), "rule__Compensation__ConditionAssignment_2_3");
			builder.put(grammarAccess.getCompensationAccess().getBodyAssignment_2_4_1(), "rule__Compensation__BodyAssignment_2_4_1");
			builder.put(grammarAccess.getActionBodyAccess().getInstructionsAssignment_1(), "rule__ActionBody__InstructionsAssignment_1");
			builder.put(grammarAccess.getBrokerSpecAccess().getBrokerHostAssignment_1(), "rule__BrokerSpec__BrokerHostAssignment_1");
			builder.put(grammarAccess.getBrokerSpecAccess().getBrokerPortAssignment_3(), "rule__BrokerSpec__BrokerPortAssignment_3");
			builder.put(grammarAccess.getEventAccess().getNameAssignment_1(), "rule__Event__NameAssignment_1");
			builder.put(grammarAccess.getEventAccess().getMsgAssignment_3(), "rule__Event__MsgAssignment_3");
			builder.put(grammarAccess.getSignalAccess().getNameAssignment_1(), "rule__Signal__NameAssignment_1");
			builder.put(grammarAccess.getSignalAccess().getMsgAssignment_3(), "rule__Signal__MsgAssignment_3");
			builder.put(grammarAccess.getTokenAccess().getNameAssignment_1(), "rule__Token__NameAssignment_1");
			builder.put(grammarAccess.getTokenAccess().getMsgAssignment_3(), "rule__Token__MsgAssignment_3");
			builder.put(grammarAccess.getDispatchAccess().getNameAssignment_1(), "rule__Dispatch__NameAssignment_1");
			builder.put(grammarAccess.getDispatchAccess().getMsgAssignment_3(), "rule__Dispatch__MsgAssignment_3");
			builder.put(grammarAccess.getRequestAccess().getNameAssignment_1(), "rule__Request__NameAssignment_1");
			builder.put(grammarAccess.getRequestAccess().getMsgAssignment_3(), "rule__Request__MsgAssignment_3");
			builder.put(grammarAccess.getInvitationAccess().getNameAssignment_1(), "rule__Invitation__NameAssignment_1");
			builder.put(grammarAccess.getInvitationAccess().getMsgAssignment_3(), "rule__Invitation__MsgAssignment_3");
			builder.put(grammarAccess.getContextAccess().getNameAssignment_1(), "rule__Context__NameAssignment_1");
			builder.put(grammarAccess.getContextAccess().getIpAssignment_3(), "rule__Context__IpAssignment_3");
			builder.put(grammarAccess.getContextAccess().getMqttAssignment_4(), "rule__Context__MqttAssignment_4");
			builder.put(grammarAccess.getComponentIPAccess().getHostAssignment_3(), "rule__ComponentIP__HostAssignment_3");
			builder.put(grammarAccess.getComponentIPAccess().getPortAssignment_5(), "rule__ComponentIP__PortAssignment_5");
			builder.put(grammarAccess.getGuardedStateActionAccess().getGuardAssignment_0_0_1(), "rule__GuardedStateAction__GuardAssignment_0_0_1");
			builder.put(grammarAccess.getGuardedStateActionAccess().getSolveGuardAssignment_0_1(), "rule__GuardedStateAction__SolveGuardAssignment_0_1");
			builder.put(grammarAccess.getGuardedStateActionAccess().getActionAssignment_1(), "rule__GuardedStateAction__ActionAssignment_1");
			builder.put(grammarAccess.getGuardedStateActionAccess().getElseactionAssignment_2_1(), "rule__GuardedStateAction__ElseactionAssignment_2_1");
			builder.put(grammarAccess.getPrintAccess().getArgsAssignment_3(), "rule__Print__ArgsAssignment_3");
			builder.put(grammarAccess.getSolveGoalAccess().getGoalAssignment_3(), "rule__SolveGoal__GoalAssignment_3");
			builder.put(grammarAccess.getSolveGoalAccess().getResVarAssignment_4_1(), "rule__SolveGoal__ResVarAssignment_4_1");
			builder.put(grammarAccess.getForwardAccess().getDestAssignment_1(), "rule__Forward__DestAssignment_1");
			builder.put(grammarAccess.getForwardAccess().getMsgrefAssignment_3(), "rule__Forward__MsgrefAssignment_3");
			builder.put(grammarAccess.getForwardAccess().getValAssignment_5(), "rule__Forward__ValAssignment_5");
			builder.put(grammarAccess.getEmitAccess().getMsgrefAssignment_1(), "rule__Emit__MsgrefAssignment_1");
			builder.put(grammarAccess.getEmitAccess().getValAssignment_3(), "rule__Emit__ValAssignment_3");
			builder.put(grammarAccess.getDelayIntAccess().getTimeAssignment_1(), "rule__DelayInt__TimeAssignment_1");
			builder.put(grammarAccess.getDelayVarAccess().getRefvarAssignment_1(), "rule__DelayVar__RefvarAssignment_1");
			builder.put(grammarAccess.getDelayVrefAccess().getReftimeAssignment_1(), "rule__DelayVref__ReftimeAssignment_1");
			builder.put(grammarAccess.getDelaySolAccess().getRefsoltimeAssignment_1(), "rule__DelaySol__RefsoltimeAssignment_1");
			builder.put(grammarAccess.getMsgCondAccess().getMessageAssignment_2(), "rule__MsgCond__MessageAssignment_2");
			builder.put(grammarAccess.getMsgCondAccess().getMsgAssignment_4(), "rule__MsgCond__MsgAssignment_4");
			builder.put(grammarAccess.getMsgCondAccess().getActionsAssignment_7(), "rule__MsgCond__ActionsAssignment_7");
			builder.put(grammarAccess.getMsgCondAccess().getIfnotAssignment_9_1(), "rule__MsgCond__IfnotAssignment_9_1");
			builder.put(grammarAccess.getNoMsgCondAccess().getActionsAssignment_2(), "rule__NoMsgCond__ActionsAssignment_2");
			builder.put(grammarAccess.getAnyActionAccess().getBodyAssignment_1(), "rule__AnyAction__BodyAssignment_1");
			builder.put(grammarAccess.getCodeRunActorAccess().getItemAssignment_1(), "rule__CodeRunActor__ItemAssignment_1");
			builder.put(grammarAccess.getCodeRunActorAccess().getArgsAssignment_4_1(), "rule__CodeRunActor__ArgsAssignment_4_1");
			builder.put(grammarAccess.getCodeRunActorAccess().getArgsAssignment_4_2_1(), "rule__CodeRunActor__ArgsAssignment_4_2_1");
			builder.put(grammarAccess.getCodeRunSimpleAccess().getItemAssignment_1(), "rule__CodeRunSimple__ItemAssignment_1");
			builder.put(grammarAccess.getCodeRunSimpleAccess().getArgsAssignment_3_0(), "rule__CodeRunSimple__ArgsAssignment_3_0");
			builder.put(grammarAccess.getCodeRunSimpleAccess().getArgsAssignment_3_1_1(), "rule__CodeRunSimple__ArgsAssignment_3_1_1");
			builder.put(grammarAccess.getExecAccess().getActionAssignment_1(), "rule__Exec__ActionAssignment_1");
			builder.put(grammarAccess.getPAtomStringAccess().getValAssignment(), "rule__PAtomString__ValAssignment");
			builder.put(grammarAccess.getPAtomicAccess().getValAssignment(), "rule__PAtomic__ValAssignment");
			builder.put(grammarAccess.getPAtomNumAccess().getValAssignment(), "rule__PAtomNum__ValAssignment");
			builder.put(grammarAccess.getPStructRefAccess().getStructAssignment_1(), "rule__PStructRef__StructAssignment_1");
			builder.put(grammarAccess.getPStructAccess().getFunctorAssignment_0(), "rule__PStruct__FunctorAssignment_0");
			builder.put(grammarAccess.getPStructAccess().getMsgArgAssignment_2(), "rule__PStruct__MsgArgAssignment_2");
			builder.put(grammarAccess.getPStructAccess().getMsgArgAssignment_3_1(), "rule__PStruct__MsgArgAssignment_3_1");
			builder.put(grammarAccess.getVariableAccess().getVarNameAssignment_1(), "rule__Variable__VarNameAssignment_1");
			builder.put(grammarAccess.getVarRefAccess().getVarNameAssignment_1(), "rule__VarRef__VarNameAssignment_1");
			builder.put(grammarAccess.getVarRefInStrAccess().getVarNameAssignment_1(), "rule__VarRefInStr__VarNameAssignment_1");
			builder.put(grammarAccess.getVarSolRefAccess().getVarNameAssignment_1(), "rule__VarSolRef__VarNameAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SimpleAgentGrammarAccess grammarAccess;

	@Override
	protected InternalSimpleAgentParser createParser() {
		InternalSimpleAgentParser result = new InternalSimpleAgentParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SimpleAgentGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimpleAgentGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
